port: 7890
socks-port: 7891
mode: rule
ipv6: true
log-level: debug  #åœ¨è°ƒè¯•ç»“æœåï¼Œæ”¹ä¸ºerroræˆ–warnï¼Œå‡å°‘æ—¥å¿—è¾“å‡ºã€‚
unified-delay: true
global-client-fingerprint: chrome
external-controller: '0.0.0.0:9090'
external-ui: /usr/local/etc/clash/ui
secret: 123456
tun:
  enable: true
  stack: gvisor   #å½“å‰åœ¨pfSenseä¸Šä¸èƒ½è®¾ç½®ä¸ºsystemã€‚
  device: tun_3000
  mtu: 9000
  auto-route: false
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver: 
    - 127.0.0.1:5335  #æŒ‡å‘mosdnsç›‘å¬åœ°å€
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - https://1.0.0.1/dns-query
    - tls://dns.google
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "+.push.apple.com"
proxies:
- name: 11               
  type: vless
  server: 88.88.88.88                           
  port: 1443                                
  uuid: 8c9e16bc-4675-411e-99bd-17f3371496a7   
  network: tcp
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: www.yahoo.com                 
  reality-opts: 
    public-key: o5Ip3BZ267wa165iroSIoKAKyI0vIzx_gB4Zh-qsx0c    
    short-id: f1aed2c2                    
  client-fingerprint: chrome                  
- name: 12                         
  type: vmess
  server: 88.88.88.88                        
  port: 2443                                     
  uuid: 8c9e16bc-4675-411e-99bd-17f3371496a7       
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  servername: www.bing.com                    
  ws-opts:
    path: "8c9e16bc-4675-411e-99bd-17f3371496a7-vm"                             
    headers:
      Host: www.bing.com                    
- name: 13                           
  type: hysteria2                                      
  server: 88.88.88.88                               
  port: 3443                                
  password: 8c9e16bc-4675-411e-99bd-17f3371496a7                          
  alpn:
    - h3
  sni: www.bing.com                               
  skip-cert-verify: true
  fast-open: true
- name: 14                            
  server: 88.88.88.88                      
  port: 4443                                    
  type: tuic
  uuid: 8c9e16bc-4675-411e-99bd-17f3371496a7       
  password: 8c9e16bc-4675-411e-99bd-17f3371496a7   
  alpn: [h3]
  disable-sni: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
  sni: www.bing.com                                
  skip-cert-verify: true
proxy-groups:
- name: è´Ÿè½½å‡è¡¡
  type: load-balance
  url: https://www.gstatic.com/generate_204
  interval: 300
  strategy: round-robin
  proxies:
    - 11                             
    - 12
    - 13
    - 14   
- name: è‡ªåŠ¨é€‰æ‹©
  type: url-test
  url: https://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
    - 11                             
    - 12
    - 13
    - 14
- name: ğŸŒé€‰æ‹©ä»£ç†èŠ‚ç‚¹
  type: select
  proxies:
    - è´Ÿè½½å‡è¡¡                                         
    - è‡ªåŠ¨é€‰æ‹©
    - DIRECT
    - 11                             
    - 12
    - 13
    - 14
rules:
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,ğŸŒé€‰æ‹©ä»£ç†èŠ‚ç‚¹
